Room.create({:title => "Dark Basement", :description => "A large, cluttered, and dark space filled with crates and old furniture covered in sheets. There is a door to the East and a broken spot in the wall to the North.", :items => nil, :image => '1.svg', :xcoord => 1, :ycoord => 1})
Room.create({:title => "Wine Cellar", :description => "This room has several large barrels and a few wine racks in it. Exits East and West.", :items => nil, :image => '2.svg', :xcoord => 2, :ycoord => 1})
Room.create({:title => "Cluttered Hallway", :description => "A passage that leads toward a lighted area. There is a door to the East and a small door to the North.", :items => nil, :image => '3.svg', :xcoord => 3, :ycoord => 1})
Room.create({:title => "Pantry", :description => "A disused pantry filled with long-spoiled supplies and kitchen wares. Exits North, West, and East.", :items => nil, :image => '4.svg', :xcoord => 4, :ycoord => 1})
Room.create({:title => "Kitchen", :description => "This kitchen appears to have been abandoned in the middle of dinner preparation- various dishes and implements still lie where they were set, the oven door hangs open.", :items => nil, :image => '5.svg', :xcoord => 5, :ycoord => 1})
Room.create({:title => "Unfinished Area", :description => "The hole in the wall leads to an unfinished space below the house. You're getting dirty crawling around in here. There is a hole in the gorund to the east, a passageway leads North.", :items => nil, :image => '6.svg', :xcoord => 1, :ycoord => 2})
Room.create({:title => "Cave", :description => "", :items => nil, :image => '7.svg', :xcoord => 2, :ycoord => 2})
Room.create({:title => "Closet", :description => "", :items => nil, :image => '8.svg', :xcoord => 3, :ycoord => 2})
Room.create({:title => "Dining Room", :description => "", :items => nil, :image => '9.svg', :xcoord => 4, :ycoord => 2})
Room.create({:title => "Study", :description => "", :items => nil, :image => '10.svg', :xcoord => 5, :ycoord => 2})
Room.create({:title => "Old Well", :description => "", :items => nil, :image => '11.svg', :xcoord => 1, :ycoord => 3})
Room.create({:title => "Attic Staircase", :description => "", :items => nil, :image => '12.svg', :xcoord => 2, :ycoord => 3})
Room.create({:title => "Roof", :description => "", :items => nil, :image => '13.svg', :xcoord => 3, :ycoord => 3})
Room.create({:title => "Library", :description => "", :items => nil, :image => '14.svg', :xcoord => 4, :ycoord => 3})
Room.create({:title => "Sitting Room", :description => "", :items => nil, :image => '15.svg', :xcoord => 5, :ycoord => 3})
Room.create({:title => "Large Closet", :description => "", :items => nil, :image => '16.svg', :xcoord => 1, :ycoord => 4})
Room.create({:title => "Crawlspace", :description => "", :items => nil, :image => '17.svg', :xcoord => 2, :ycoord => 4})
Room.create({:title => "Closet Under Stairs", :description => "", :items => nil, :image => '18.svg', :xcoord => 3, :ycoord => 4})
Room.create({:title => "Stairs", :description => "", :items => nil, :image => '19.svg', :xcoord => 4, :ycoord => 4})
Room.create({:title => "Parlor", :description => "", :items => nil, :image => '20.svg', :xcoord => 5, :ycoord => 4})
Room.create({:title => "Master Bedroom", :description => "", :items => nil, :image => '21.svg', :xcoord => 1, :ycoord => 5})
Room.create({:title => "Hallway", :description => "", :items => nil, :image => '22.svg', :xcoord => 2, :ycoord => 5})
Room.create({:title => "Bathroom", :description => "", :items => nil, :image => '23.svg', :xcoord => 3, :ycoord => 5})
Room.create({:title => "Bedroom", :description => "", :items => nil, :image => '24.svg', :xcoord => 4, :ycoord => 5})
Room.create({:title => "Foyer", :description => "", :items => nil, :image => '25.svg', :xcoord => 5, :ycoord => 5})
Exit.create({:nsew => 'north'})
Exit.create({:nsew => 'south'})
Exit.create({:nsew => 'west'})
Exit.create({:nsew => 'east'})

room = Room.find(1)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(2)
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(3)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(4)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(5)
room.exits << Exit.find_or_create_by(nsew: 'west')
room = Room.find(6)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'south')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(7)
room.exits << Exit.find_or_create_by(nsew: 'west')
room = Room.find(8)
room.exits << Exit.find_or_create_by(nsew: 'south')
room = Room.find(9)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(10)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'west')
room = Room.find(11)
room.exits << Exit.find_or_create_by(nsew: 'south')
room = Room.find(12)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(13)
room.exits << Exit.find_or_create_by(nsew: 'west')
room = Room.find(14)
room.exits << Exit.find_or_create_by(nsew: 'south')
room = Room.find(15)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'south')
room = Room.find(16)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(17)
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'south')
room = Room.find(18)
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(19)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(20)
room.exits << Exit.find_or_create_by(nsew: 'north')
room.exits << Exit.find_or_create_by(nsew: 'south')
room.exits << Exit.find_or_create_by(nsew: 'west')
room = Room.find(21)
room.exits << Exit.find_or_create_by(nsew: 'south')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(22)
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'east')
room = Room.find(23)
room.exits << Exit.find_or_create_by(nsew: 'west')
room = Room.find(24)
room.exits << Exit.find_or_create_by(nsew: 'west')
room.exits << Exit.find_or_create_by(nsew: 'south')
room = Room.find(25)
room.exits << Exit.find_or_create_by(nsew: 'south')
Artifact.create({:room_id => 11, :hidden => false, :obscures => true, :name => 'desk', :purpose => '2', :unlock => 'search, check, inspect, open', :title => "", :description => 'a dusty desk covered in paperwork and stationery.'})
Artifact.create({:room_id => 11, :hidden => true, :obscures => false, :name => 'key', :purpose => 'open door in room 23', :unlock => 'use, turn, insert', :title => "", :description => 'a plain grey skeleton key'})
Artifact.create({:room_id => 2, :hidden => false, :obscures => false, :name => 'folded map', :purpose => 'waste of time', :unlock => nil, :title => "", :description => 'a mildly tattered copy of the 1978 Shell Oil Roadmap of Florida. Probably not so helpful. Good luck folding it back up.'})
