 # This is the code needed to build all 25 rooms plus the connections between them on the map.

(1..5).each do |y|
  (1..5).each do |x|
    Room.create({:title => nil, :description => nil, :items => nil, :image => nil, :xcoord => x, :ycoord => y})
  end
end
["n", "s", "e", "w"].each do |dir|
  Exit.create({:nsew => dir})
end
room = Room.find(1)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(2)
room.exits << Exit.find_or_create_by(nsew: 'w')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(3)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(4)
room.exits << Exit.find_or_create_by(nsew: 'w')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(5)
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(6)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 's')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(7)
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(8)
room.exits << Exit.find_or_create_by(nsew: 's')
room = Room.find(9)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(10)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(11)
room.exits << Exit.find_or_create_by(nsew: 's')
room = Room.find(12)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(13)
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(14)
room.exits << Exit.find_or_create_by(nsew: 's')
room = Room.find(15)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 's')
room = Room.find(16)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(17)
room.exits << Exit.find_or_create_by(nsew: 'w')
room.exits << Exit.find_or_create_by(nsew: 's')
room = Room.find(18)
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(19)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 'w')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(20)
room.exits << Exit.find_or_create_by(nsew: 'n')
room.exits << Exit.find_or_create_by(nsew: 's')
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(21)
room.exits << Exit.find_or_create_by(nsew: 's')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(22)
room.exits << Exit.find_or_create_by(nsew: 'w')
room.exits << Exit.find_or_create_by(nsew: 'e')
room = Room.find(23)
room.exits << Exit.find_or_create_by(nsew: 'w')
room = Room.find(24)
room.exits << Exit.find_or_create_by(nsew: 'w')
room.exits << Exit.find_or_create_by(nsew: 's')
room = Room.find(25)
room.exits << Exit.find_or_create_by(nsew: 's')
