style="height:420px;width:750px;border:1px solid #ccc;font:16px/26px Georgia, Garamond, Serif;overflow:auto;"



1 |      1 |      1 | Dark Basement       | A large, cluttered, and dark space filled with crates and old furniture covered in sheets. There is a door to the East and a broken spot in the wall to the North.                                                                                                                                                                  |       | 1.svg  |          | 2018-07-24 18:51:06.38433  | 2018-07-24 18:51:06.38433
2 |      2 |      1 | Wine Cellar         | This room has several large barrels and a few wine racks in it. Exits East and West.                                                                                                                                                                                                                                                |       | 2.svg  |          | 2018-07-24 18:51:06.387041 | 2018-07-24 18:51:06.387041
3 |      3 |      1 | Cluttered Hallway   | A passage that leads toward a lighted area. There is a door to the East and a small door to the North.                                                                                                                                                                                                                              |       | 3.svg  |          | 2018-07-24 18:51:06.388696 | 2018-07-24 18:51:06.388696
4 |      4 |      1 | Pantry              | A disused pantry filled with long-spoiled supplies and kitchen wares. Exits North, West, and East.                                                                                                                                                                                                                                  |       | 4.svg  |          | 2018-07-24 18:51:06.390249 | 2018-07-24 18:51:06.390249
5 |      5 |      1 | Kitchen             | This kitchen appears to have been abandoned in the middle of dinner preparation- various dishes and implements still lie where they were set, the oven door hangs open. Exit is to the West.                                                                                                                                        |       | 5.svg  |          | 2018-07-24 18:51:06.391762 | 2018-07-24 18:51:06.391762
6 |      1 |      2 | Unfinished Area     | The hole in the wall leads to an unfinished space below the house. You're getting dirty crawling around in here. There is a hole in the gorund to the East, a passageway leads North.                                                                                                                                               |       | 6.svg  |          | 2018-07-24 18:51:06.393334 | 2018-07-24 18:51:06.393334
7 |      2 |      2 | Cave                | The hole leads to a small residence. You can barely sit up in this space. Exit is to the West.                                                                                                                                                                                                                                      |       | 7.svg  |          | 2018-07-24 18:51:06.394827 | 2018-07-24 18:51:06.394827
8 |      3 |      2 | Closet              | The small door leads to this closet space, in the corner is a small ornate locked chest. Exit is to the South.                                                                                                                                                                                                                      |       | 8.svg  |          | 2018-07-24 18:51:06.396705 | 2018-07-24 18:51:06.396705
9 |      4 |      2 | Dining Room         | The table is set for a grand meal. Someone's place setting has been disturbed. You wonder what was for dinner. Exits are to the North, South, and East.                                                                                                                                                                             |       | 9.svg  |          | 2018-07-24 18:51:06.398931 | 2018-07-24 18:51:06.398931
10 |      5 |      2 | Study               | Someone's comfortable workspace. A book lies open on the chair. Exits are to the North and West.                                                                                                                                                                                                                                    |       | 10.svg |          | 2018-07-24 18:51:06.400395 | 2018-07-24 18:51:06.400395
11 |      1 |      3 | Old Well            | The unfinished space leads to an area with what was apparently the house's well at some point, but which most recently seems to have been used as a trash can. It is boarded up, but you can see down into it. Exit is to the South.                                                                                                |       | 11.svg |          | 2018-07-24 18:51:06.401928 | 2018-07-24 18:51:06.401928
12 |      2 |      3 | Attic Staircase     | A narrow and dusty staircase leads almost straight up to the East. You wonder where your climbing gear is. Exits are North and East.                                                                                                                                                                                                |       | 12.svg |          | 2018-07-24 18:51:06.403437 | 2018-07-24 18:51:06.403437
13 |      3 |      3 | Roof                | You are on the roof! You have escaped! Congratulations. However, now you are on the roof. And there is no ladder or easy way down, and it is dark and windy. No direction looks particularly safe... pick a direction to try! Hopefully you will not plummet to your doom. Exits are North, South, East, and West.                  |       | 13.svg |          | 2018-07-24 18:51:06.404877 | 2018-07-24 18:51:06.404877
14 |      4 |      3 | Library             | Someone had some money. This library is filled with hundreds of books, some of which are locked in glass cabinets. There is a potted plant here which is eyeing you with some curiousity. You re-read that sentence and worry maybe you shouldn't linger here too long. Exit is to the South.                                       |       | 14.svg |          | 2018-07-24 18:51:06.406311 | 2018-07-24 18:51:06.406311
15 |      5 |      3 | Sitting Room        | Nobody is sitting in the sitting room. Thankfully. You would like to sit, too, but everything is dusty and it seems like someone might appear at any moment to shoo you away. Exits are North and South.                                                                                                                            |       | 15.svg |          | 2018-07-24 18:51:06.407817 | 2018-07-24 18:51:06.407817
16 |      1 |      4 | Large Closet        | The Master Bedroom Closet is dark and cluttered with so many Anne Rice Novel gothy outfits and pointy shoes. it's really hot in here for some reason. There is a small door in the wall under one of the shelves. Exits are North and East.                                                                                         |       | 16.svg |          | 2018-07-24 18:51:06.409291 | 2018-07-24 18:51:06.409291
17 |      2 |      4 | Crawlspace          | This crawlspace is almost completely black. There's a rickety baby carriage here which is too large to have fit in through the door. Nothing spooky about that. Exits are to the West west through a small door and South.                                                                                                          |       | 17.svg |          | 2018-07-24 18:51:06.410727 | 2018-07-24 18:51:06.410727
18 |      3 |      4 | Closet Under Stairs | This tiny closet under the stairs is jammed with brooms. Someone liked their brooms a lot. There is not a single dustpan. These people were odd. Exit is to the East.                                                                                                                                                               |       | 18.svg |          | 2018-07-24 18:51:06.412156 | 2018-07-24 18:51:06.412156
19 |      4 |      4 | Stairs              | A wide and welcoming staircase winds up to the second floor. Portraits of the family line the walls, although, someone has glued googly eyes to all of the faces. Exits are North to go up the stairs, West to a closet door, and East.                                                                                             |       | 19.svg |          | 2018-07-24 18:51:06.414199 | 2018-07-24 18:51:06.414199
20 |      5 |      4 | Parlor              | You've always wondered what people used a parlor for. These people liked their stuffed and mounted small game. The walls and tables are filled with rabbits, weasels, marmots, stoats, chipmunks... all their glassy, beady eyes follow you as you explore the room. So far, none of them have moved. Exits are North, South, West. |       | 20.svg |          | 2018-07-24 18:51:06.415847 | 2018-07-24 18:51:06.415847
21 |      1 |      5 | Master Bedroom      | The Master Bedroom is mostly empty. It seems the Lord of the house expired in his bed some decades ago. His toothy grin greets you as you enter the room. Atop the covers, something juts from his clenched right hand. Exits are East and South. No, you cannot just jump out one of the windows.                                  |       | 21.svg |          | 2018-07-24 18:51:06.417308 | 2018-07-24 18:51:06.417308
22 |      2 |      5 | Hallway             | This Hallway connects the upstairs bedrooms- many of the other rooms doors are quite securely locked. Exits are West and East.                                                                                                                                                                                                      |       | 22.svg |          | 2018-07-24 18:51:06.419016 | 2018-07-24 18:51:06.419016
23 |      3 |      5 | Bathroom            | There's a bowling ball in the toilet. Other than that, this seems like a normal turn-of-the-century bathroom. The medicine cabinet door is hanging open. Exits are West and East.                                                                                                                                                   |       | 23.svg |          | 2018-07-24 18:51:06.420533 | 2018-07-24 18:51:06.420533
24 |      4 |      5 | Bedroom             | This guest bedroom is painted with bloodstains. Whoever did it left the paintbrush behind as well. They did a pretty poor job of making the stains- you were not fooled for a second. Exits are West and South.                                                                                                                     |       | 24.svg |          | 2018-07-24 18:51:06.422205 | 2018-07-24 18:51:06.422205
25 |      5 |      5 | Foyer               | The foyer is cluttered with debris- you can't get anywhere near the door, so, there's no way out of the house here. There's an old suede jacket on a hook. Exit is to the South.                                                                                                                                                    |       | 25.svg |          | 2018-07-24 18:51:06.423865 | 2018-07-24 18:51:06.423865
